name: API Monitor

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  check-api:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check API Updates
      env:
        CRON_SECRET: ${{ secrets.CRON_SECRET }}
        API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
      run: |
        echo "Starting API check..."
        
        if [ -z "${API_ENDPOINT}" ]; then
          echo "API_ENDPOINT is not set. Please set it in GitHub Secrets."
          exit 0
        fi
        
        response=$(curl -s -w "\n%{http_code}" -X POST \
          -H "Authorization: Bearer ${CRON_SECRET}" \
          -H "Content-Type: application/json" \
          "${API_ENDPOINT}/api/check-updates")
        
        http_code=$(echo "$response" | tail -n1)
        body=$(echo "$response" | sed '$d')
        
        echo "Response: $body"
        echo "HTTP Code: $http_code"
        
        if [ "$http_code" -ne 200 ]; then
          echo "API check failed with status code: $http_code"
          exit 1
        fi
        
        echo "API check completed successfully"
